# Generated by Django 2.1.3 on 2018-11-02 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181103_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_ddate',
            new_name='article_date',
        ),
    ]
